version: '3.8'

services:
  telegram-bot:
    build: .
    container_name: telegram-text-image-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      # Optional: Mount a volume for persistent logs
      - ./logs:/app/logs
    # Memory limit (optional, comment out if not supported)
    mem_limit: 512m
    # CPU limit (optional, comment out if not supported)  
    cpus: 0.5

# Create logs directory if it doesn't exist
volumes:
  logs:
